import Sprockell.System

prog = [
		Const 1 RegE,
		Const 0 RegB,
		Compute Add RegA RegB RegB,
		Store RegE (Deref RegB),
		Const 2 RegE,
		Const 4 RegB,
		Compute Add RegA RegB RegB,
		Store RegE (Deref RegB),
		Const 1 RegE,
		Const 8 RegB,
		Compute Add RegA RegB RegB,
		Store RegE (Deref RegB),
		Const 0 RegB,
		Compute Add RegA RegB RegB,
		Load (Deref RegB) RegE,
		Push RegE,
		Pop RegD,
		Const 4 RegB,
		Compute Add RegA RegB RegB,
		Load (Deref RegB) RegE,
		Compute Add RegD RegE RegE,
		Const 8 RegB,
		Compute Add RegA RegB RegB,
		Store RegE (Deref RegB),
		Const 8 RegB,
		Compute Add RegA RegB RegB,
		Load (Deref RegB) RegE,
		Push RegE,
		Pop RegD,
		Const 3 RegE,
		Compute Lt RegD RegE RegE,
		Branch RegE (Abs 43),
		Const 8 RegB,
		Compute Add RegA RegB RegB,
		Load (Deref RegB) RegE,
		Push RegE,
		Pop RegD,
		Const 2 RegE,
		Compute Mul RegD RegE RegE,
		Const 8 RegB,
		Compute Add RegA RegB RegB,
		Store RegE (Deref RegB),
		Jump (Abs 48),
		Nop ,
		Const 3 RegE,
		Const 8 RegB,
		Compute Add RegA RegB RegB,
		Store RegE (Deref RegB),
		Nop 
		]
main = run 1 prog
